Script started on 2022-02-09 17:13:54-05:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="271" LINES="30"]
]0;gy24@remotel3: ~/cs214/labs/05[01;32mgy24@remotel3[00m:[01;34m~/cs214/labs/05[00m$ clojure(reduce + [1 2 3])[11Pclojure
[KClojure 1.10.1
[Kuser=> [Kuser=> [Kuser=> script 4.script[C[C[C[C[C[C[C(sumSquares '(1 2 3))[C[C[C[C[C[C[C[Cdefn sumSquares [seq] (reduce + (map (fn [x] (* x x)) seq)))[C[C[C[C[C[C[C[K(defn sumSquares [seq] (reduce + (map (fn [x] (* x x)) seq)))
[K#'user/sumSquares
user=> [Kuser=> [Kuser=> (sumQu[Kaure[K[K[K[K[KSquares '(1 2 3)[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[K(sumSquares '(1 2 3))
14
user=> [Kuser=> [Kuser=> (sumSquares '(1 2 3 4 5)[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[K(sumSquares '(1 2 3 4 5))
55
user=> [Kuser=> [Kuser=> (sumSquares [-1 -2 -3 0 1][C[C[C[C[C[C[C[C[C[C[C[C[C[C)[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[K(sumSquares [-1 -2 -3 0 1])
15
user=> [Kuser=> [Kuser=> 
[K]0;gy24@remotel3: ~/cs214/labs/05[01;32mgy24@remotel3[00m:[01;34m~/cs214/labs/05[00m$ exit

Script done on 2022-02-09 17:15:25-05:00 [COMMAND_EXIT_CODE="0"]
