TempTester: Temperature.class TempTester.class

Temperature.class: Temperature.java
	javac -deprecation Temperature.java

TempTester.class: TempTester.java
	javac -deprecation TempTester.java

clean:
	rm -f *.class *~ *# *.o

